### PR TITLE
[WIP-FIX] Add a --auto-approve flag to layerform kill

### PR DESCRIPTION
**Pull request by hi-hi-ray**
## Why this matters

Add a --auto-approve flag to the kill command that makes the cli skip the confirmation when killing a layer instance.

## Solution

- Fixed typo error
- Add kill flag

###### Notes

The Flag check was already created in the code.
Related to: #62

### CODE REVIEW

**Review by vieiralucas — CHANGES_REQUESTED** [review]
Hey, hello @hi-hi-ray.

Thank you so much for the PR!

I think you forgot to change it so that the `flag` get's passed to the `Kill::Run` method.

Here:
https://github.com/ergomake/layerform/blob/bf01ccddef104e7631b647fb1d0f1645f5997f97/cmd/cli/kill.go#L60
It is currently hardcoded to pass `false`, this PR should change this to get the value from the `flag`.
Something like this:
```go
		autoApprove, err := cmd.Flags().GetBool("auto-approve")
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s\n", errors.Wrap(err, "fail to get --auto-approve flag, this is a bug in layerform"))
			os.Exit(1)
			return
		}

		err = kill.Run(ctx, layerName, instanceName, autoApprove, vars)
```

Lastly, I think it would be pretty cool if we change the `e2e.yml` tests that test the `kill` command to use that flag instead of using the `yes` command.

Over here:
https://github.com/ergomake/layerform/blob/bf01ccddef104e7631b647fb1d0f1645f5997f97/.github/workflows/e2e.yml#L80-L85
Just change line `82` to use the new flag
```yaml
          layerform kill bar test_bar --auto-approve
```

PS: thank you for fixing that typo ❤️

**Comment by hi-hi-ray** [comment]
I will work it this week in your suggestions. Thank You so much for the help!!

**Comment by lucasfcosta** [comment]
Hey @hi-hi-ray let us know if you need any help on this, happy to provide any further guidance if necessary! And thanks again for contributing. Please don't feel the need to rush this, just thought I'd check in to make sure you get help if you need anything.

**Comment by hi-hi-ray** [comment]
Hey, would you mind to put a label of WIP on this PR?

**Pull request closed without merging**
